import Foundation

let folder = URL(fileURLWithPath: FileManager.default.currentDirectoryPath).appendingPathComponent("build/voice-review")
let data = try Data(contentsOf: folder.appendingPathComponent("results.json"))
var records = try JSONSerialization.jsonObject(with: data) as! [[String: Any]]
for index in records.indices {
    if records[index]["error"] == nil, let file = records[index]["file"] as? String,
       let audio = try? Data(contentsOf: folder.appendingPathComponent(file)) {
        records[index]["audio"] = "data:audio/wav;base64," + audio.base64EncodedString()
    }
}
let json = String(data: try JSONSerialization.data(withJSONObject: records, options: [.sortedKeys]), encoding: .utf8)!
    .replacingOccurrences(of: "<", with: "\\u003c")
let findingsURL = folder.appendingPathComponent("findings.json")
let findings = (try? String(contentsOf: findingsURL, encoding: .utf8)) ?? "{}"
let page = #"""
<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Spokn · Voice review</title>
<style>
:root{color-scheme:dark;font:15px/1.6 -apple-system,BlinkMacSystemFont,Arial,sans-serif;background:#151719;color:#e9eaec}*{box-sizing:border-box}body{margin:0}main{max-width:1140px;margin:0 auto;padding:52px 26px 80px}header{border-bottom:1px solid #343638;padding-bottom:30px;margin-bottom:26px}.eyebrow{color:#ef9a71;font-weight:650;font-size:12px;letter-spacing:.14em;text-transform:uppercase}h1{font-size:42px;letter-spacing:-1.4px;line-height:1.15;margin:14px 0}h2{font-size:24px;letter-spacing:-.4px;margin:0 0 12px}p{margin:8px 0;color:#b8bec5}.intro{max-width:810px}.toolbar{display:flex;gap:18px;align-items:center;flex-wrap:wrap;margin:26px 0}.group{display:flex;gap:5px;background:#24272b;border-radius:10px;padding:4px}button,select{font:inherit;color:inherit;border:0;cursor:pointer;background:transparent;padding:7px 13px;border-radius:7px}button.active{background:#ef9a71;color:#20170f;font-weight:650}button:focus-visible,select:focus-visible{outline:2px solid #ef9a71;outline-offset:2px}select{background:#24272b;min-width:200px}.rate{margin-left:auto}.case-note{background:#27241f;border:1px solid #584838;border-radius:12px;padding:17px 20px;margin:20px 0;color:#f1d4b9}.cards{display:grid;grid-template-columns:1fr 1fr;gap:18px}.card{border:1px solid #36393e;border-radius:16px;padding:22px;background:#1c1f23}.card h3{margin:0 0 18px;font-size:17px;display:flex;justify-content:space-between;align-items:center}.badge{font-size:11px;font-weight:550;letter-spacing:.06em;text-transform:uppercase;color:#a8b1bc}.label{font-size:11px;letter-spacing:.1em;font-weight:600;text-transform:uppercase;color:#97a2af;margin:18px 0 5px}.text{white-space:pre-wrap;margin:0;color:#e9eaec}.transcript{color:#d6bc92}.metrics{color:#919ca8;font-size:12px;margin-top:12px}.error{color:#ffb19b}audio{width:100%;height:40px;margin-top:20px}.limits{margin-top:36px;border-top:1px solid #343638;padding-top:20px;font-size:13px;color:#9fa9b4}code{background:#2b3036;border-radius:4px;padding:2px 5px}a{color:#efb48b}.summary{display:flex;gap:22px;flex-wrap:wrap;margin-top:22px;font-size:13px}.summary strong{color:#f0f1f3;font-size:19px;margin-right:4px}.empty{padding:25px} @media(max-width:720px){main{padding:30px 18px}.cards{grid-template-columns:1fr}h1{font-size:34px}.rate{margin-left:0}.toolbar{gap:12px}}
</style><main><header><div class="eyebrow">Spokn / Local voice diagnostics</div><h1>What the voices actually say.</h1><p class="intro">Alba in English and Jürgen in German, generated through Spokn’s current Pocket TTS pipeline. Compare raw input with written-out alternatives, then inspect the recognizer transcript alongside the audio.</p><div class="summary" id="summary"></div></header>
<div class="toolbar"><div class="group" aria-label="Language"><button class="active" data-language="en">Alba · English</button><button data-language="de">Jürgen · German</button></div><label>Example <select id="category"></select></label><div class="group rate" aria-label="Playback speed"><button class="active" data-rate="1">1×</button><button data-rate="1.75">1.75×</button><button data-rate="2">2×</button></div></div>
<h2 id="title"></h2><div id="note" class="case-note" hidden></div><div class="cards" id="cards"></div>
<div class="limits"><strong>How to interpret this review</strong><p>Speech recognition can reveal missing words or misread shortcuts, but its spelling, capitalization, and number formatting are not pronunciation scores. These are two stochastic generations per input, not a statistical quality benchmark. No direct listening judgment is claimed.</p><p>Clips use the actual app’s chunk boundaries and model settings. Spelled-out alternatives are experiments and are not installed as app behavior. Speed buttons change this browser’s audio playback rate; its time stretching can differ from the native app. All audio is embedded in this page and plays locally.</p></div></main>
<script id="clips" type="application/json">
"""# + json + #"""
</script><script id="findings" type="application/json">
"""# + findings.replacingOccurrences(of: "<", with: "\\u003c") + #"""
</script><script>
const clips=JSON.parse(document.querySelector('#clips').textContent),findings=JSON.parse(document.querySelector('#findings').textContent);
const labels={'ordinary':'Ordinary sentences','speed-symbols':'Speed symbols and decimals','shortcut':'Keyboard shortcuts','technical':'Technical terms, versions, and units','names':'Names across languages','bullets':'Lists and paragraph breaks','long-sentence':'Long sentences and chunk boundaries'};
let language='en',rate=1;
const category=document.querySelector('#category');for(const [key,label] of Object.entries(labels)){const option=document.createElement('option');option.value=key;option.textContent=label;category.append(option)}
const seconds=clips.reduce((sum,c)=>sum+c.duration,0);document.querySelector('#summary').innerHTML=`<span><strong>${clips.length}</strong> generated chunks</span><span><strong>${Math.round(seconds/60)}</strong> minutes of audio</span><span><strong>2</strong> trials per input</span>`;
function render(){document.querySelectorAll('audio').forEach(a=>a.pause());const key=category.value;document.querySelector('#title').textContent=labels[key];const note=findings[language+'.'+key]||findings[key];document.querySelector('#note').hidden=!note;document.querySelector('#note').textContent=note||'';const root=document.querySelector('#cards');root.replaceChildren();const chosen=clips.filter(c=>c.language===language&&c.category===key).sort((a,b)=>a.trial-b.trial||a.chunk-b.chunk||(a.variant==='raw'?-1:1));for(const c of chosen){const card=document.createElement('article');card.className='card';const heading=document.createElement('h3');heading.textContent=c.variant==='raw'?'Raw input':'Spelled-out alternative';const badge=document.createElement('span');badge.className='badge';badge.textContent=`Trial ${c.trial} · Chunk ${c.chunk}`;heading.append(badge);card.append(heading);for(const [label,value,cls]of [['Text sent to the model',c.text,'text'],['Recognizer transcript',c.error||c.transcript,c.error?'text error':'text transcript']]){const l=document.createElement('div');l.className='label';l.textContent=label;const p=document.createElement('p');p.className=cls;p.textContent=value;card.append(l,p)}if(c.audio){const audio=document.createElement('audio');audio.controls=true;audio.preload='none';audio.src=c.audio;audio.playbackRate=rate;audio.addEventListener('play',()=>{document.querySelectorAll('audio').forEach(other=>{if(other!==audio)other.pause()})});card.append(audio)}const m=document.createElement('div');m.className='metrics';m.textContent=`${c.duration.toFixed(2)} s audio · ${c.generationSeconds.toFixed(2)} s generation + alignment · detected ${c.detectedLanguage} · ${(c.clippedFraction*100).toFixed(3)}% samples at full scale`;card.append(m);root.append(card)}}
document.querySelectorAll('[data-language]').forEach(b=>b.onclick=()=>{language=b.dataset.language;document.querySelectorAll('[data-language]').forEach(x=>x.classList.toggle('active',x===b));render()});document.querySelectorAll('[data-rate]').forEach(b=>b.onclick=()=>{rate=Number(b.dataset.rate);document.querySelectorAll('[data-rate]').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('audio').forEach(a=>a.playbackRate=rate)});category.onchange=render;render();
</script></html>
"""#
try page.write(to: folder.appendingPathComponent("index.html"), atomically: true, encoding: .utf8)
print("Wrote \(folder.appendingPathComponent("index.html").path) (\(records.count) clips)")
